@echo off

REM Creating a temporary conda environment for installation...
conda create -n search_replace_tool_temp_environment python=3.10 -y

REM Activating the tempoaray conda environment...
conda activate search_replace_tool_temp_environment

REM Installing pip...
conda install pip -y

REM Installing dependencies from requirements.txt...
pip install -r requirements.txt

REM Creating the dist directory if it doesn't exist...
if not exist dist mkdir dist

REM Building the executable using PyInstaller...
pyinstaller --onefile src/search_replace.py -y

REM Copying the README.md file to the dist directory...
copy README.md dist\

REM Copying the contents of the data folder to the dist directory...
xcopy data dist\ /s /e /y

REM Deactivate the tempoaray conda environment...
conda deactivate

REM Removing the tempoaray conda environment...
conda remove -n search_replace_tool_temp_environment --all -y
